#%RAML 1.0 NamedExample
{
  "name" : "Venkat",
  "dob" : "1985-12-30",
  "employee-id": 1001,
  "designation": "Technical Architect",
  "email" : "venkat@hcl.com",
  "joinDate" : "2001-01-01",
  "phoneNumber" :"91-9988776633", 
  "location" : "Indore"
}
