http:
  host: "localhost"
  port: "8081"
  path: "/api/*"
  
db:
  host: "aws-emp-mysql-db.cpunnoztebf0.us-east-1.rds.amazonaws.com" 
  port: "3306"
  username: "admin"
  schema: "usr_managemnt"
  password: "![9CMNKCJwpakcPzDJHzyQGg==]"

  