#%RAML 1.0
title: employee-api

types:
  empType: !include Datatypes/employeeType.raml

/employees:
  get:
    queryParameters:
      fromRecord : string
    responses:
      200:
        body:
           application/json:
            type: empType[]
  post:
   body:
    application/json:
      type: empType            

  put:
   body:
    application/json:
      type: empType

  delete:
    body:
     application/json:
       type: empType
                                                                                                                                                        

  